# Generated by Django 5.2.17 on 2026-09-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_user', models.CharField(max_length=20)),
                ('documento_user', models.CharField(max_length=20, unique=True)),
                ('nombres_user', models.CharField(max_length=100)),
                ('apellidos_user', models.CharField(max_length=100)),
                ('correo_user', models.EmailField(max_length=254, unique=True)),
                ('contrasena_user', models.CharField(max_length=128)),
                ('telefono_user', models.CharField(blank=True, max_length=20)),
                ('programa', models.CharField(max_length=150)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
