# Generated by Django 5.2.17 on 2026-09-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(primary_key=True, serialize=False)),
                ('nit_company', models.CharField(max_length=20, unique=True)),
                ('nombre_company', models.CharField(max_length=100)),
                ('correo_company', models.EmailField(max_length=254, unique=True)),
                ('telefono_company', models.CharField(blank=True, max_length=20)),
                ('activo', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
