# Generated by Django 5.2.17 on 2026-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_company_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
